# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.nosugar.io/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii", "--indent", "2"]
  - repo: https://github.nosugar.io/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.nosugar.io/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.nosugar.io/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.nosugar.io/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: tests/data/.*
  - repo: local
    hooks:
#      - id: check-test-data
#        name: check test json data ids and columns match
#        language: system
#        entry: ./scripts/check.sh
#        pass_filenames: false
      - id: python-no-print
        name: check for print()
        description: 'A quick check for the `print()` built-in function'
        entry: '\bprint\('
        language: pygrep
        types: [python]
        exclude: ^scripts/
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        'types_or': [python, pyi]
        require_serial: true
        args: ["--scripts-are-modules"]
        minimum_pre_commit_version: '2.9.2'
#      - id: pyright
#        name: pyright
#        entry: pyright
#        language: node
#        pass_filenames: false
#        types: [python]
#        additional_dependencies: ["pyright@1.1.229"]
